.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. vidcoin_qt test_vidcoin_qt
clean: FORCE
	$(MAKE) -C .. vidcoin_qt_clean test_vidcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_vidcoin_qt_check
vidcoin-qt vidcoin-qt.exe: FORCE
	 $(MAKE) -C .. vidcoin_qt
